//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIVIET
    {
        public int MaBV { get; set; }
        public string TenBV { get; set; }
        public Nullable<int> MaDMBV { get; set; }
        public string HinhAnhBV { get; set; }
        public string ChiTietBV { get; set; }
    
        public virtual DMBAIVIET DMBAIVIET { get; set; }
    }
}
